version: "3.7"
services:
  graphite:
    container_name: graphite-statsd-metrics
    image: graphiteapp/graphite-statsd:latest
    restart: always
    ports: 
      - 8000:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
      - 8180:8080
    volumes:
      - .\statsd:/opt/statsd/config
  grafana:
    container_name: grafana-metrics
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .\grafana:/var/lib/grafana
    links:
      - graphite
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - graphite